-- The remote project already owns this table. `if not exists` also makes the
-- migration usable in a clean local Supabase stack while remote schema access
-- is unavailable.
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text not null,
  title text not null,
  excerpt text not null,
  published_at timestamptz not null,
  featured boolean not null default false,
  tags text[] not null default '{}',
  cover_key text,
  linkedin_embed jsonb,
  display_order integer not null default 0
);

create unique index if not exists posts_slug_unique on public.posts (slug);

alter table public.posts drop constraint if exists posts_slug_format;
alter table public.posts
  add constraint posts_slug_format
  check (char_length(slug) between 1 and 80 and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
  not valid;

alter table public.posts drop constraint if exists posts_content_limits;
alter table public.posts
  add constraint posts_content_limits
  check (
    char_length(btrim(title)) between 1 and 120
    and char_length(btrim(excerpt)) between 1 and 300
    and display_order between 0 and 9999
    and cardinality(coalesce(tags, '{}')) <= 10
  )
  not valid;

alter table public.posts drop constraint if exists posts_linkedin_embed_safe;
alter table public.posts
  add constraint posts_linkedin_embed_safe
  check (
    linkedin_embed is null
    or (
      jsonb_typeof(linkedin_embed) = 'object'
      and jsonb_typeof(linkedin_embed -> 'compact') = 'object'
      and jsonb_typeof(linkedin_embed -> 'full') = 'object'
      and (linkedin_embed #>> '{compact,src}') is not null
      and (linkedin_embed #>> '{full,src}') is not null
      and (linkedin_embed #>> '{compact,src}') ~ '^https://www[.]linkedin[.]com/embed/'
      and (linkedin_embed #>> '{full,src}') ~ '^https://www[.]linkedin[.]com/embed/'
      and (
        not (linkedin_embed -> 'compact' ? 'width')
        or (
          jsonb_typeof(linkedin_embed #> '{compact,width}') = 'number'
          and (linkedin_embed #>> '{compact,width}')::numeric between 320 and 800
        )
      )
      and (
        not (linkedin_embed -> 'full' ? 'width')
        or (
          jsonb_typeof(linkedin_embed #> '{full,width}') = 'number'
          and (linkedin_embed #>> '{full,width}')::numeric between 320 and 800
        )
      )
      and (
        not (linkedin_embed -> 'compact' ? 'height')
        or (
          jsonb_typeof(linkedin_embed #> '{compact,height}') = 'number'
          and (linkedin_embed #>> '{compact,height}')::numeric between 200 and 1000
        )
      )
      and (
        not (linkedin_embed -> 'full' ? 'height')
        or (
          jsonb_typeof(linkedin_embed #> '{full,height}') = 'number'
          and (linkedin_embed #>> '{full,height}')::numeric between 200 and 1000
        )
      )
    )
  )
  not valid;

-- Validation fails before access policies change if legacy rows are unsafe.
alter table public.posts validate constraint posts_slug_format;
alter table public.posts validate constraint posts_content_limits;
alter table public.posts validate constraint posts_linkedin_embed_safe;

alter table public.posts enable row level security;

-- Remove legacy policies whose names and predicates are unknown. Recreate the
-- complete intended policy set below.
do $policy_cleanup$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'posts'
  loop
    execute format('drop policy %I on public.posts', existing_policy.policyname);
  end loop;
end
$policy_cleanup$;

revoke all on table public.posts from anon, authenticated;
grant select on table public.posts to anon, authenticated;
grant insert, update, delete on table public.posts to authenticated;

do $sequence_grants$
declare
  posts_sequence text;
begin
  posts_sequence := pg_get_serial_sequence('public.posts', 'id');
  if posts_sequence is not null then
    execute format('revoke all on sequence %s from anon', posts_sequence);
    execute format('grant usage, select on sequence %s to authenticated', posts_sequence);
  end if;
end
$sequence_grants$;

create policy "posts_public_read"
on public.posts
for select
to anon, authenticated
using (true);

create policy "posts_admin_insert"
on public.posts
for insert
to authenticated
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "posts_admin_update"
on public.posts
for update
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "posts_admin_delete"
on public.posts
for delete
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

comment on table public.posts is
  'Public blog posts. Anonymous users can read; only users with app_metadata.role=admin can write.';
