-- Baseline captured and registered from the linked `andresbadillo-web` project before the
-- security remediation. It intentionally preserves the pre-remediation grants
-- and read policy so the following migration owns the security delta.
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  published_at date not null,
  featured boolean not null default false,
  tags text[] not null default '{}',
  cover_key text,
  linkedin_embed jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  display_order integer not null default 0
);

create index if not exists posts_display_order_idx
on public.posts (display_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

drop trigger if exists trg_posts_set_updated_at on public.posts;
create trigger trg_posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

alter table public.posts enable row level security;

drop policy if exists "Public can read posts" on public.posts;
create policy "Public can read posts"
on public.posts
for select
to anon, authenticated
using (true);

-- These were the effective remote privileges at capture time. The hardening
-- migration that follows replaces them with least privilege.
grant all on table public.posts to anon, authenticated;

do $baseline_sequence_grants$
declare
  posts_sequence text;
begin
  posts_sequence := pg_get_serial_sequence('public.posts', 'id');
  if posts_sequence is not null then
    execute format('grant all on sequence %s to anon, authenticated', posts_sequence);
  end if;
end
$baseline_sequence_grants$;
